name: Postman CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, master]

jobs:
  run-postman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Authenticate Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run Postman Collection
        run: |
          postman collection run "Postman/Reqress_Assurdly.json" \
            -r cli,html --bail

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-cli-reports
          path: postman-cli-reports
